<div class="container">
	<form class="form-signin">
		<h1 class="form-signin-heading">Sign in</h1>
		<div class="alert alert-error" id="invalid-cred" style="display:none">
			Your username or password is invalid
		</div>
		<input type="text" class="input-block-level" placeholder="Email address" name="email">
		<input type="password" class="input-block-level" placeholder="Password" name="password">
		<button class="btn btn-large btn-primary btn-block" id="login-button">Sign in</button>
		<p style="margin-top:5px;"><a href="<?php echo $this->baseUrl('/auth/forgot/'); ?>">Forgot Password?</a></p>
		<p style="margin-left:110px;margin-top:100px;"><img src="<?php echo $this->baseUrl('img/logo.jpg'); ?>"></p>
		<footer class="text-center">&copy; Options Community Services <?php echo date('Y'); ?></footer>
	</form>
</div>