<div class="container">
	<form class="form-signin">
		<h1 class="form-signin-heading"><small>Reset</small><br><span style="margin-left:-3px;">Password</span></h1>
		<div id="reset-box">
			<div class="alert alert-error" id="invalid-email" style="display:none">
				That is not a valid email
			</div>
			<input type="text" class="input-block-level" placeholder="Email address" name="email">
			<button class="btn btn-large btn-primary btn-block"  id="reset-button">Send password reset email</button>
		</div>

		<p style="margin-top:5px;"><a href="<?php echo $this->baseUrl('/'); ?>">&laquo; Return to login</a></p>
		<p style="margin-left:110px;margin-top:100px;"><img src="<?php echo $this->baseUrl('img/logo.jpg'); ?>"></p>
		<footer class="text-center">&copy; Options Community Services <?php echo date('Y'); ?></footer>
	</form>
</div>