<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Options Community Services</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Le styles -->
	<link href="<?php echo $this->baseUrl('css/bootstrap.min.css'); ?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl('css/bootstrap-responsive.min.css'); ?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl('css/common.css'); ?>" rel="stylesheet">
	<style type="text/css">
	.form-signin {
		max-width: 300px;
		margin: 0 auto 20px;
	}
	.form-signin .checkbox {
		margin-bottom: 10px;
	}
	.form-signin-heading {
		padding-top: 20px;
		margin-bottom: 25px;
		font-size: 56px;
	}
	.form-signin input[type="text"], .form-signin input[type="password"] {
		font-size: 16px;
		height: auto;
		margin-bottom: 15px;
		padding: 7px 9px !important;
	}
	</style>

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Fav and touch icons -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png">
	<link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico');?>">
</head>

<body>
<?php echo $this->layout()->content ?>

	<!-- Le javascript
	================================================== --> 
	<!-- Placed at the end of the document so the pages load faster --> 
	<script src="<?php echo $this->baseUrl('js/jquery.js'); ?>"></script> 
	<script src="<?php echo $this->baseUrl('js/bootstrap.min.js'); ?>"></script> 
	<script src="<?php echo $this->baseUrl('js/frp/auth.js'); ?>"></script>
</body>
</html>
