
<?php
$url = $this->frp_url . "auth/forgot/?code=" . $this->reset_string;
?>
<html>
    <head>
    </head>
    <body>
        <p>
            Hi <?php echo $this->name; ?>,
        </p>
        A password reset request has been submitted. If this has been submitted in error, please disregard this message. This password reset request will be valid for 24 hours.
        <p>
            To reset your password, please follow the following link. <a href="<?php echo $url; ?>"><?php echo $url; ?></a> This will reset your password and email you a temporary password.
        </p>
        <p>Once logged in, you will be able to change this password if you choose.</p>

    </body>
</html>

